before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X {{ .ModulePath }}/app.version={{ .Version }} -X {{ .ModulePath }}/app.commit={{ .FullCommit }} -X {{ .ModulePath }}/app.date={{ .Date }}
  ignore:
    - goos: windows
      goarch: arm64
archives:
- id: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  wrap_in_directory: '{{ .ProjectName }}'
  files:
    - LICENSE
    - static/*
    - template/*
  format_overrides:
    - goos: windows
      format: zip
dockers:
  - goos: linux
    goarch: amd64

    # Templates of the Docker image names.
    image_templates:
      - "r.deso.tech/whoami/{{ .ProjectName }}:latest"
      - "r.deso.tech/whoami/{{ .ProjectName }}:{{ .Version }}"

    # Skips the docker push. Could be useful if you also do draft releases.
    # If set to auto, the release will not be pushed to the docker repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    skip_push: auto

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile

    use: buildx

    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

    extra_files:
      - app
      - go.mod
      - go.sum
      - main.go
      - server
      - static
      - template
      - view
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .ProjectName }}-SNAPSHOPT-{{ .ShortCommit }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^src:'
      - Merge pull request
      - Merge branch
      - go mod tidy
