openapi: '3.0.0'
info:
  title: whoami
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
tags:
  - name: app
    description: Information about the app instance
  - name: environment
    description: Information about the run environment
components:
  schemas:
    version:
      type: object
      properties:
        version:
          type: string
        major:
          type: integer
          format: int32
          minimum: 0
        minor:
          type: integer
          format: int32
          minimum: 0
        patch:
          type: integer
          format: int32
          minimum: 0
        commit:
          type: string
        buildDate:
          type: string
          format: date-time
    memory:
      type: object
      properties:
        total:
          type: integer
          format: int64
          minimum: 0
        available:
          type: integer
          format: int64
          minimum: 0
        used:
          type: integer
          format: int64
          minimum: 0
        usedPercent:
          type: number
          format: double
          minimum: 0
          maximum: 100
paths:
  /version:
    get:
      tags:
        - app
      summary: Returns the running version
      responses:
        '200':
          description: A JSON object describing the app version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/version'
  /memory:
    get:
      tags:
        - environment
      summary: Returns the available RAM
      responses:
        '200':
          description: A JSON object describing the available RAM
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/memory'
