name: Release

on:
  push:
    tags:
      - v*

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-20.04
    env:
      GO_VERSION: 1.16.3
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Publish GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

      - name: Upload release assets
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: https://dl.google.com/go/go${{ env.GO_VERSION }}.linux-amd64.tar.gz
          extra_files: static template LICENSE
          md5sum: false
          sha256sum: true
          overwrite: true
