name: Release

on:
  push:
    tags:
      - v*

jobs:
  docker-windows:
    name: Push Windows Images
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GNU make
        run: choco install make

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: r.deso.tech
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push docker images
        run: make docker-windows

  docker-linux:
    name: Push Linux images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Install buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: r.deso.tech
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push Docker images
        run: make docker-linux

  docker-shared:
    name: Push Shared Tags
    runs-on: ubuntu-latest
    needs: [docker-windows, docker-linux]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: r.deso.tech
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push manifest lists
        run: make docker-shared

  github-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: docker-shared
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.17'

      - name: Cross compile & archive release artifacts
        run: make xcompress

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*
